version: '3.8'

services:
  app:
    container_name: react-native-app
    build: .
    ports:
      - "8081:8081"
      - "19000:19000"  # Expo DevTools
      - "19001:19001"  # Tunnel Expo
      - "19002:19002"  # Expo Web
      - "19006:19006"  # Serveur Web Expo
    volumes:
      - .:/app  # Monte le dossier local dans le conteneur
      - /app/node_modules  # Ignore le dossier node_modules pour éviter les conflits
    stdin_open: true  # Permet d'interagir avec Expo CLI
    tty: true
